# Generated by Django 2.1 on 2019-05-17 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 17), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TextField(default='11:03', verbose_name='Time'),
        ),
    ]
