# Generated by Django 2.1 on 2019-05-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190517_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default='11:04', verbose_name='Time'),
        ),
    ]
