# Generated by Django 2.1 on 2019-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190517_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default='19:33', verbose_name='Time'),
        ),
    ]
