# Generated by Django 2.1 on 2019-05-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20190518_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default='14:48', verbose_name='Time'),
        ),
    ]
