# Generated by Django 2.2.6 on 2019-11-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20190518_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2019, 11, 1), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default='10:38', verbose_name='Time'),
        ),
    ]
