# Generated by Django 2.2.6 on 2020-06-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_auto_20200626_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_saver', to=settings.AUTH_USER_MODEL),
        ),
    ]
